@startuml
'https://plantuml.com/class-diagram


entity 支付方式{
    支付方式编码
    支付方式名称 当面付、手机网页支付
    状态
}

entity 支付渠道{
     渠道名称
     状态
}
entity 支付渠道方式{
    支付渠道
    支付方式
}

entity 支付渠道商户{
    所属方
    支付渠道
    支付渠道商户ID
    支付渠道商户名称
}

entity 支付渠道应用{
    支付渠道
    支付渠道应用ID
    支付渠道商户
    应用公钥
    应用私钥
    渠道公钥
}

entity 商户{
    所属人
    商户名称
}

entity 商户应用{
    商户ID
    支付应用
}

entity 支付单{
    支付单号
    商户
    商户应用
    支付方式
    支付渠道
    支付渠道商户
    支付渠道应用
    支付渠道单号
    支付金额
    支付状态
}
entity 退款单{
    退款单号
    支付单号
    退款金额
    退款状态
    退款渠道单号
    支付渠道
    支付渠道商户
    支付渠道应用
    支付渠道单号
}

entity 分账单{
    分账单号
    支付单号

}
entity 对外付款单{
    付款单号
}

entity 授权商户支付渠道应用{
    商户ID
    支付渠道应用
    支付渠道
}


商户 ||--o{ 授权商户支付渠道应用
授权商户支付渠道应用 }|--|{ 支付渠道应用

商户 ||--o{ 商户应用

支付渠道 ||--o{ 支付渠道商户


支付渠道 ||--o{ 支付渠道方式

支付方式 }|--|{ 支付渠道方式

支付渠道商户 ||--o{ 支付渠道应用


支付单 ||--o{ 退款单
支付单 ||--o{ 分账单




@enduml
