@startuml
'https://plantuml.com/sequence-diagram

actor 用户 #FFCCCC
participant 商户系统 #FFCC99
participant 支付中心 #CCFFCC
participant 支付渠道 #CCCCFF




autonumber 1.1


group 支付方式选择

用户 -> 商户系统: 创建订单

商户系统 -> 支付中心: 生成预支付单

支付中心 --> 商户系统: 支付单号

商户系统 -> 支付中心: 提供支付场景，获取支付方式

支付中心 --> 商户系统: 返回可选支付方式

商户系统 --> 用户: 展示可选支付方式

用户 -> 商户系统: 选择支付方式

商户系统 -> 支付中心: 发起支付

end

autonumber 2.1
group 支付路由


支付中心 -> 支付中心: 根据支付场景,支付方式，
支付中心 -> 支付中心: 枚举出可选支付渠道应用
支付中心 -> 支付中心: 选定支付渠道应用
end

autonumber 3.1
group 发起支付
支付中心 -> 支付渠道: 生成渠道预支付单
支付渠道 --> 支付中心: 返回预支付单号
支付中心 -> 支付中心: 构建支付参数
支付中心 -> 商户系统: 返回支付参数

商户系统 -> 用户:返回支付参数


end
autonumber 4.1
group 唤起支付
用户 -> 支付中心: 唤起支付
支付中心 -> 支付渠道: 唤起支付
支付渠道-> 支付渠道: 用户支付

支付渠道 -> 支付中心: 返回支付结果


支付中心 -> 商户系统: 展示支付结果

商户系统 -> 用户: 支付成功

end





@enduml
