@startuml
'https://plantuml.com/class-diagram

package 第三方支付渠道{

    entity 支付渠道{
        渠道ID
        渠道名称
        状态
    }

    enum 支付产品{
            渠道ID
            支付产品
            支付产品名称

            状态
        }
    enum 支付方式{
        支付方式编码:WEB,H5,APP,当面付、扣款、预授权、刷脸
        支付方式名称
        状态
    }

    entity 支付渠道应用{
        支付渠道应用ID
        支付渠道ID
        支付渠道商户ID
        支付渠道商户名称
        应用公钥
        应用私钥
        渠道公钥
        +支付产品: List<支付产品>
    }

    支付渠道 ||--o{ 支付产品
    支付渠道 ||--o{ 支付渠道应用
}

package 支付系统{

    package 商户系统{

        entity 服务商ISV{
                商户ID
                所属人
                商户名称
            }

            entity 商户{
                商户类型
                商户ID
                所属人
                服务商ISV
                商户名称
                +支付渠道应用: List<支付渠道应用>
            }

            entity 商户应用{
                商户应用ID
                商户ID
                支付应用

            }
    }


    entity 支付交易{
        支付交易号

        '商户
        商户ID
        商户应用ID

        主题
        描述
        商品详情

        '订单原始
        商户原始单号
        支付门店
        支付终端

        '支付渠道
        支付渠道
        支付方式
        支付渠道商户ID
        支付渠道应用ID
        支付渠道单号

        ' 金额
        货币
        支付金额
        支付者实付
        商户优惠
        平台优惠
        商户实收
        手续费

        ' 支付者
        支付者类型: 企业、个人
        支付者渠道ID: openID
        支付系统ID

        ' 支付方式
        收银类型: WBE,H5,APP,TAP,POS,SCAN
        收银渠道

        支付状态
        创建时间
        过期时间
        支付时间
        退款时间

    }

    entity 交易退款{
        退款单号
        支付交易号
        退款金额: 金额
        退款状态: 退款状态枚举
        退款渠道单号: 渠道单号
        支付渠道ID
        支付渠道商户ID
        支付渠道应用ID
        支付渠道单号: 渠道单号
        创建时间
        更新时间
    }

    entity 分账单{
        分账单号
        支付交易号
        支付交易: 支付交易
        创建时间
        更新时间
    }

    entity 转账单{
        转账单号
        创建时间
        更新时间
    }

    服务商ISV ||--o{ 商户
    商户 ||--o{ 商户应用



    支付交易 ||--o{ 分账单
    支付交易 ||--o{ 交易退款






}

package 领域服务{

    enum 金额 {
        货币
        金额值
    }


    enum 支付状态枚举 {
        待支付
        支付成功
        支付失败
    }

    enum 退款状态枚举 {
        待退款
        退款成功
        退款失败
    }

    class 支付服务 {
        +创建支付交易(支付交易: 支付交易): 支付交易
        +发起支付(支付交易: 支付交易): Boolean
        +处理支付回调(支付交易: 支付交易, 回调数据: Map<String, String>): Boolean
    }

    class 退款服务 {
        +创建退款单(退款单: 退款单): 退款单
        +发起退款(退款单: 退款单): Boolean
    }

    class 分账服务 {
        +创建分账单(分账单: 分账单): 分账单
        +处理分账(分账单: 分账单): Boolean
    }
}
@enduml
